version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1

    working_directory: /go/src/github.com/tellytv/go.schedulesdirect
    steps:
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: gometalinter --config=.gometalinter.json ./...
